version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      # Update & install dependencies
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y unzip git curl
      # Install Composer
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      # Install project dependencies
      - composer install

  pre_build:
    commands:
      - echo Running pre-build steps...
      - composer dump-autoload

  build:
    commands:
      - echo Running unit tests...

  post_build:
    commands:
      - echo Build and tests completed.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
